---
homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - homebrew/cask-drivers

homebrew_installed_packages:
  - git
  - zsh
  - neovim
  - iperf
  - tmux
  - wget
  - tree
  - wakeonlan
  - antigen
  - minicom
  - pass
  - pwgen
  - bat
  - prettyping
  - diff-so-fancy
  - noti
  - heroku
  - assh
  - telnet
  - tio
  - git-extras
  - git-flow
  - platformio

homebrew_cask_apps:
  - font-jetbrains-mono
  - iterm2
  - spotify
  - alfred
  - balenaetcher
  - nextcloud
  - gpg-suite-no-mail
  - presentation
  - visual-studio-code
  - ferdi
  - jetbrains-toolbox
  - gitkraken
  - vagrant
  - virtualbox
  - ftdi-vcp-driver
